#! /bin/bash
set -exo nounset

export LFS=/mnt/lfs
test -d $LFS ||
mkdir -v $LFS

test -d $LFS/sources || \
mkdir -v $LFS/sources

find $LFS/sources -mindepth 1 -maxdepth 1 -type f -executable -delete

cp * $LFS/sources

pushd $LFS/sources
./lfs-2-preparing-the-host-system
./lfs-4.2-creating-the-LFS-tools-directory
./lfs-4.3-adding-the-LFS-user
su -c $LFS/sources/lfs-5-constructing-a-temporary-system - lfs
tar acf /tools.txz /tools
./lfs-5.37-changing-ownership
./lfs-6.2-preparing-virtual-kernel-file-systems
popd

cp * $LFS/tools

chroot "$LFS" /tools/bin/env -i \
    HOME=/root                  \
    TERM="$TERM"                \
    PS1='\u:\w\$ '              \
    LFS=/ \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin \
    /tools/bin/bash --login +h building-the-lfs-system

chroot $LFS /tools/bin/env -i            \
    HOME=/root TERM=$TERM PS1='\u:\w\$ ' \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin   \
    LFS=/ \
    /tools/bin/bash --login lfs-6.72-stripping-again-2
chroot $LFS /tools/bin/env -i            \
    HOME=/root TERM=$TERM PS1='\u:\w\$ ' \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin   \
    LFS=/ \
    /tools/bin/bash --login lfs-6.73-cleaning-up-1

chroot "$LFS" /usr/bin/env -i              \
    HOME=/root TERM="$TERM" PS1='\u:\w\$ ' \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin     \
    LFS=/ \
    /bin/bash --login lfs-6.74-cleaning-up-2
