#! /bin/sh
set -exo nounset

export LFS=/mnt/lfs

cp * $LFS/sources

pushd $LFS/sources
./lfs-2-preparing-the-host-system
./lfs-4.2-creating-the-LFS-tools-directory
./lfs-4.3-adding-the-LFS-user
su -c $LFS/sources/lfs-5-constructing-a-temporary-system - lfs
./lfs-5.27-changing-ownership
./lfs-6.2-preparing-virtual-kernel-file-systems
popd

cp * $LFS/tools

chroot "$LFS" /tools/bin/env -i \
    HOME=/root                  \
    TERM="$TERM"                \
    PS1='\u:\w\$ '              \
    LFS="$LFS" \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin \
    /tools/bin/bash --login +h building-the-lfs-system