#! /bin/sh
set -exo nounset

source ~/.bashrc

cd $LFS/sources

./tcl-core
./expect
./dejagnu
./check
./ncurses
./bash
./bison
./bzip2
./coreutils
./diffutils
./file
./findutils
./gawk
./gettext
./grep
./gzip
./m4
./make
./patch
./perl
./sed
./tar
./texinfo
./util-linux
./xz