#! /bin/sh
set -exo nounset

cd $LFS/sources

rm -rf linux-4.12.7
tar xf linux-4.12.7.tar.xz
cd linux-4.12.7

make mrproper

make INSTALL_HDR_PATH=dest headers_install
cp -rv dest/include/* /tools/include